package com.crms.customer_crm_backend.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column; // Lombok for getters, setters, etc.
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Data;

@Entity // Specifies that this class is an entity and maps to a database table
@Table(name = "users") // Maps to the 'users' table in the database
@Data // Lombok annotation to generate getters, setters, toString, equals, and hashCode methods
public class User {

    @Id // Specifies the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Indicates that the primary key is automatically generated by the database
    private Long id;

    @Column(unique = true, nullable = false, length = 50) // Maps to a column named 'user_name', must be unique and not null
    private String userName;

    @Column(nullable = false, length = 255) // Maps to 'password_hash' column
    private String passwordHash;

    @Column(unique = true, length = 100) // Maps to 'email' column, must be unique
    private String email;

    @Column(length = 20) // Maps to 'phone_number' column
    private String phoneNumber;

    @Column(name = "created_at", updatable = false) // Maps to 'created_at' column, not updatable
    private LocalDateTime createdAt;

    // Pre-persist to set creation timestamp
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}